### PR TITLE
Enable nexus auth for sbt

### PR DESCRIPTION
**Pull request by der-eismann**

### CODE REVIEW

**Review by bjoernhaeuser — APPROVED** [review]
Is this only required for pushing?

**Comment by der-eismann** [comment]
No, but everything else needs to be done per project.

**Comment by bjoernhaeuser** [comment]
But then you also need todo something on the 'build image' part?

**Comment by der-eismann** [comment]
> But then you also need todo something on the 'build image' part?

My idea of the ticket was to only secure the uploading of artifacts. Do you also want to have auth for downloading artifacts?

**Comment by bjoernhaeuser** [comment]
> > But then you also need todo something on the 'build image' part?
> 
> My idea of the ticket was to only secure the uploading of artifacts. Do you also want to have auth for downloading artifacts?

Nope, uploading is fine, was just confused by your first response. Lets goooo

**Review by svenwltr — APPROVED** [review]

**Pull request merged**
